services:
  postgres:
    image: postgres:16
    container_name: jobtracker-postgres
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: jobtracker_pass
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_data:/var/lib/postgresql/data

volumes:
  jobtracker_data: